language: node_js  #設置語言

node_js: 10.16.0  #設置相應的版本

cache:
    apt: true
    directories:
        - node_modules # 緩存不經常更改的內容

before_install:
  - echo 安装hexo相关环境...

#install:
  # - npm install -g cnpm --registry=https://registry.npm.taobao.org
  #- cnpm install

before_script:
  - echo 正在清空缓存静态文件...
  - hexo clean                      # 清除缓存静态文件
  - echo 正在生成静态文件...
  - hexo g                          # 生成静态文件
  - cd ./public
  - ls -l

script:
  - echo 开始部署...
  - git init
  - git config --global user.name "monsterchan"                          # 修改name
  - git config --global user.email "$646597336@qq.com"                        # 修改email
  - git add ./
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  # GH_TOKEN是在Travis中配置token的名稱

after_script:
  - echo 部署完成！

branches:
  only:
    - master                                                                # 只監測master分支，master是我的博客源碼分支的名稱，可根據自己情況設置
env:
  global:
    - GH_REF: github.com/monsterchan/monsterchan.github.io                                        # 设置 github 项目仓库地址
    - GH_username: <monsterchan>                                               # 设置 github 用户名           
    - GH_useremail: <646597336@qq.com>                                             # 设置 github 绑定邮箱地址
