language: node_js
node_js: 10.16.0
cache:
  directories:
  - node_modules
before_install:
- echo 安装hexo相关环境...
- openssl aes-256-cbc -K $encrypted_c689b32daa6d_key -iv $encrypted_c689b32daa6d_iv
    -in .travis/id_rsa_6blog.enc -out .travis/id_rsa_6blog -d
- echo 配置git信息
- git config --global user.name "monsterchan"
- git config --global user.email "$646597336@qq.com"
install:
- npm install hexo-cli -g
- npm install
script:
- echo 开始部署...
- npm run deploy
after_script:
- echo 部署完成！
branches:
  only:
  - master
monsterchan/catblog:
- openssl aes-256-cbc -K $encrypted_c689b32daa6d_key -iv $encrypted_c689b32daa6d_iv
  -in .travis/id_rsa_6blog.enc -out .travis/id_rsa_6blog -d
