language: node_js
node_js: 10.16.0
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_c689b32daa6d_key -iv $encrypted_c689b32daa6d_iv
  -in .travis/id_rsa_travis.enc -out .travis/id_rsa_travis -d
- echo 安装hexo相关环境...
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_travis
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "monsterchan"
- git config --global user.email "$646597336@qq.com"
#before_script:
#- echo 正在清空缓存静态文件...
#- hexo clean
#- echo 正在生成静态文件...
#- hexo g
#- cd ./public
#- ls -l
install:
  - npm install hexo-cli -g
  - npm install
script:
- echo 开始部署...
- npm run deploy
#- git init
#- git add .
#- git commit -m "update_in_travis.yml"
#- git push   "https://${GH_TOKEN}@${GH_REF}" master:master

after_script:
- echo 部署完成！
branches:
  only:
  - master
#env:
#  global:
# - GH_REF: github.com/monsterchan/monsterchan.github.io
# - GH_username: "<monsterchan>"
# - GH_useremail: "<646597336@qq.com>"
