language: node_js
node_js: 10.16.0
cache:
  directories:
  - node_modules
before_install:
- echo 配置ssh信息
- ls
- cd .ssh
- ls
- chmod 600 id_rsa_travis
- eval $(ssh-agent)
- ssh-add id_rsa_travis
- echo 配置git信息
- git config --global user.name "monsterchan"
- git config --global user.email "$646597336@qq.com"
install:
- npm install hexo-cli -g
- npm install
script:
- echo 开始部署...
- npm run deploy
after_script:
- echo 部署完成！
branches:
  only:
  - master
