language: node_js
node_js: 10.16.0
cache:
  directories:
  - node_modules
before_install:
- echo 配置ssh信息
- chmod 600 ~/.ssh/id_rsa_travis
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_travis
- cp .travis/ssh_config ~/.ssh/config
- echo 配置git信息
- git config --global user.name "monsterchan"
- git config --global user.email "$646597336@qq.com"
install:
- npm install hexo-cli -g
- npm install
script:
- echo 开始部署...
- npm run deploy
after_script:
- echo 部署完成！
branches:
  only:
  - master
