# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 陈   # 网站的标题，可能用在各种布局的页面中
subtitle: You are my sunshine！          # 网站子标题
#description: Just let me know you in my life!       # 网站的描述性
keywords: chenkequan 陈科全          # 网站的关键字
#author: 沐喵         # 网站的作者
language: zh-Hans       # 网站采用语言，要跟/theme/***/languages/**.yml下的文件名对应。
#timezone:              # 网站的时区

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: monsterchan.github.io      # 网站的url，如果不在域名根目录，应包含子目录，且root要设置为`/子目录/`
root: /                          # 网站的根目录
permalink: :year/:month/:day/:title/             #文章永久链接的形成模版。每一篇文章都有唯一的url。
permalink_defaults:              #文章永久链接中，各部分的默认值。

# Directory
source_dir: source                # 网站中源文件（比如Markdown啊什么的所在的文件夹）
public_dir: public             # 生成的静态网站的目录
tag_dir: tags                     # 标签页所在的文件夹
archive_dir: archives           # 文档页所在的文件夹
category_dir: categories         # 类别也所在的文件夹
code_dir: downloads/code           # 代码也所在的文件夹
i18n_dir: :lang                       # 国际语言所在的文件夹
skip_render:                             # 忽略文档清单

# Writing
new_post_name: :title.md # File name of new posts # 默认新建文档名，`:title`为变量，指文档标题，也可用其他变量
default_layout: post              #新建文档的默认布局
titlecase: false # Transform title into titlecase  # 是否要把标题中的首字符大写
external_link: true # Open external links in new tab # 是否要在新开tab中打开外链
filename_case: 0              # 文件名是否小写敏感
render_drafts: false         # 是否渲染草稿
post_asset_folder: true        # 是否启用资源文件夹。如启用，新建文档同时建立同名的资源文件夹       {% asset_img 资源对象名 提示文字 %}
                                      #<img src="{asset_path full-image.jpg %}/>"               {% asset_link 资源对象名 显示文字 %}
                                     #{% fullimage 资源对象名, 替代文字, 标题 %}
relative_link: false               # 是否把站内资源的链接改为站内相对链接。建议关闭
future: true                       # 文档中指定为未来时间创建
highlight: 
  enable: true                      # 是否开启代码高亮功能
  line_number: true                 # 代码块中是否在前面加上行号
  auto_detect: false               # 是否自动检测代码块的语言（比如xml、JavaScript、mermaid等）
  tab_replace:                           # 用什么字符来代替tab(`\t`)字符
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''                  # 主页所在路径，默认为''
  per_page: 10               # 主页的索引页包含文章数量，如未定义，则采用根目录下的`per_page`值
  order_by: -date             # 文章（Post类型）排序属性，`-`为降序
  
# Category & Tag
default_category: uncategorized          # 文章（Post类型）排序属性，`-`为降序
category_map:                             # 对文档中的分类字段进行映射。建立分类文件夹时采用映射后的字符串
tag_map:                                  # 对文档中的标签字段进行映射。建立标签文件夹时采用映射后的字符串

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
     github: git@github.com:monsterchan/monsterchan.github.io.git
     #github: https://github.com/monsterchan/catcode.github.io.git
     #coding: 
  branch: master

# backup
backup:
  type: git
  message: backup my blog of https://yourname.github.io/
  repository:
    # github: https://github.com/monsterchan/monsterchan.github.io.git,backup
    # coding: https://git.coding.net/monsterchan/monsterchan.git,backup

#RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
#live2d配置
live2d:
 enable: true
 scriptFrom: local
 pluginRootPath: live2dw/  # 插件在站点上的根目录(相对路径)
 pluginJsPath: lib/        # 脚本文件相对与插件根目录路径
 pluginModelPath: assets/  # 模型文件相对与插件根目录路径
      # scriptFrom: jsdelivr # jsdelivr CDN
      # scriptFrom: unpkg # unpkg CDN
      # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
 tagMode: false        # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
 debug: false           # 调试, 是否在控制台输出日志
 model:
   use: nvpu      # npm-module package name
        # use: wanko # 博客根目录/live2d_models/ 下的目录名
        # use: ./wives/wanko # 相对于博客根目录的路径
        # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
   scale: 1         #缩放比例
   hHeadPos: 0.5
   vHeadPos: 0.618
 display:
   superSample: 2        #图像细腻层度
   position: right
   width: 180
   height: 365
   hOffset: 55              #  +往右移动(相对position反的)
   vOffset: 0              # +往上移动
 mobile:
   show: true
   scale: 0.5
 react:
   opacity: 0.9          # 透明度
   opacityOnHover: 1
# name:
#   canvas: caciya
#   div: caciya
# dev:
#   border: false
 dialog:
  enable: true
  hitokoto: true


search:
  path: search.xml
  field: post
  format: html
  limit: 10000
  content: true