# site name
prefixName: 桜と猫
siteName: chan
# favicon and site master avatar
# 网页标签图片
favicon: /images/favicon.ico
#首页头像
avatar: /img/myimg/cat.jpg
#映射自定义域名
url: http://chenkequan.cn
description: Live is Fantasting
#github+cdn (jsdeliver)
cdn: https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6
pjax: 1
# 1开启
mathjax: 0

notice: 目前正在开发中...
#加载load图片
lazyloadImg: https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg
#顶部菜单
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  ##客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

#主页排序类型:-1
# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
#首页文章显示编号
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(8).jpg.webp
  - https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6/img/cover/(9).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /待定/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/437122003, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}


#你的站点建立日期
# your site build time or founded date
siteBuildingTime: 20/06/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/monsterchan, img: /img/social/github.png}
  csdn: {url: https://blog.csdn.net/ckq707718837, img: /img/social/csdn.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=1890872610, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/SwimmingElephant/activities, img: /img/social/zhihu.png}
  jianshu: {url: https://www.jianshu.com/u/887f106f4a13, img: /img/social/jianshu.png}
  wechat: {url: /#, qrcode: /img/myimg/wechat.png, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/monsterchan, fa: fa-github, color: 333}
  wechat: {url: /# , qrcode: /img/myimg/wechat.png, fa: fa-wechat, color: dd4b39}
  qq: {url: /#, qrcode: /img/myimg/qq.png , fa: fa-qq, color: 25c6fe}
  
 #赞赏二维码（其中wechatSQ是赞赏单页面的赞赏码图片
donate:
  alipay: /img/myimg/donate/ALiPayQR.png
  wechat: /img/myimg/donate/WeChanQR.png
  wechatSQ: /img/myimg/donate/WeChanQR.png

  #首页视频地址为，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/monsterchan/cdn@1.6
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

 #左下角aplayer播放器配置 主要改id和server这两项，修改详见[aplayer文档] 
aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true


#Valine评论配置
# Valine
valine: true
v_appId: abjgEzjHH9MKHgJmfwjKRuxY-gzGzoHsz
v_appKey: QnyxXfkHI82ehTHQOmv275Jx

